### ISSUE TITLE
报错：ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by sweetboxwwy** [ChHanXiao/license-plate-recoginition#1]
Traceback (most recent call last):
  File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/train.py", line 100, in <module>
    main(args)
  File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/train.py", line 57, in main
    drop_last=True,
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 266, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\utils\data\sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by ChHanXiao** [comment]
debug看下dataloader是否读到数据，确认下cfg里数据路径是否正确

**Comment by sweetboxwwy** [comment]
> debug看下dataloader是否读到数据，确认下cfg里数据路径是否正确
cfg的路径没有问题，是不是config里面数据的路径问题呢
data:
  train:
    img_dir:
    - /home/hanxiao/data/lp-data/train-1
    - /home/hanxiao/data/lp-data/train-2
    - /home/hanxiao/data/lp-data/train-3
    - /home/hanxiao/data/lp-data/train-4
    - /home/hanxiao/data/lp-data/train-green-1
    - /home/hanxiao/data/lp-data/train-green-2
    - /home/hanxiao/data/lp-data/train-green
    # - /home/hanxiao/data/lp-data/train-green-same
    - datasets/CCPD2019/crop/train_sub
    - datasets/CCPD2020/crop/train
    # - datasets/CCPD2020/crop/val
  val:
    img_dir:
    # - datasets/CCPD2019/crop/test
    - datasets/CCPD2020/crop/test

**Comment by ChHanXiao** [comment]
img_dir: 写你自己的路径呢，工程附带生成车牌[gen_data.py](https://github.com/ChHanXiao/license-plate-recoginition/blob/main/gen_data.py)

**Comment by sweetboxwwy** [comment]
> 
可不可以直接使用您训练的模型呢，是inference.py吗。有一些参数不知道填哪个

**Comment by ChHanXiao** [comment]
可以

**Comment by sweetboxwwy** [comment]
> 可以

请问我参数填的是这样的
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", type=str, default="val", help="task to run, test or val")
    parser.add_argument("--config",
                        default=r'E:\PycharmProjects\Vehicle_Detection\license-plate-recoginition-main\license-plate-recoginition-main\workspace\lp0211\logs-2022-02-28-15-51-23\train_cfg.yml',
                        type=str, help="model config file(.yml) path")
    parser.add_argument("--model",
                        default=r'E:\PycharmProjects\Vehicle_Detection\license-plate-recoginition-main\license-plate-recoginition-main\workspace\lp_model_best.pth',
                        type=str, help="ckeckpoint file(.ckpt) path")
    parser.add_argument("--path",
                        default=r'E:\PycharmProjects\Vehicle_Detection\plate_main\plate_main\inference\images\12.jpg',
                        type=str, help="img path")
但还是报错：
C:\Users\wangwy\Anaconda3\python.exe E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py
C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:252: FutureWarning: IAAAdditiveGaussianNoise is deprecated. Please use GaussNoise instead
  warnings.warn("IAAAdditiveGaussianNoise is deprecated. Please use GaussNoise instead", FutureWarning)
C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:290: FutureWarning: This IAAPiecewiseAffine is deprecated. Please use PiecewiseAffine instead
  warnings.warn("This IAAPiecewiseAffine is deprecated. Please use PiecewiseAffine instead", FutureWarning)
C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:222: FutureWarning: IAASharpen is deprecated. Please use Sharpen instead
  warnings.warn("IAASharpen is deprecated. Please use Sharpen instead", FutureWarning)
C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:165: FutureWarning: This augmentation is deprecated. Please use Emboss instead
  warnings.warn("This augmentation is deprecated. Please use Emboss instead", FutureWarning)
[LP-rec][02-28 16:13:30]INFO:Creating model...
initial net weights successful!
Traceback (most recent call last):
  File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py", line 121, in <module>
    main(args)
  File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py", line 92, in main
    LP_Rec = Perdictor(cfg, args.model, logger,)
  File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py", line 52, in __init__
    self.task.model.load_state_dict(ckpt["state_dict"])
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PlateNet_multi_1:
	Missing key(s) in state_dict: "outconv1.0.block.0.weight", "outconv1.0.block.0.bias", "outconv1.0.block.2.weight", "outconv1.0.block.2.bias", "outconv1.0.block.4.weight", "outconv1.0.block.4.bias", "outconv1.0.block.6.weight", "outconv1.0.block.6.bias", "stage2.0.block.0.weight", "stage2.0.block.0.bias", "stage2.0.block.2.weight", "stage2.0.block.2.bias", "stage2.0.block.4.weight", "stage2.0.block.4.bias", "stage2.0.block.6.weight", "stage2.0.block.6.bias", "stage2.4.block.0.weight", "stage2.4.block.0.bias", "stage2.4.block.2.weight", "stage2.4.block.2.bias", "stage2.4.block.4.weight", "stage2.4.block.4.bias", "stage2.4.block.6.weight", "stage2.4.block.6.bias", "stage2.5.weight", "stage2.5.bias", "stage2.5.running_mean", "stage2.5.running_var", "outconv2.0.block.0.weight", "outconv2.0.block.0.bias", "outconv2.0.block.2.weight", "outconv2.0.block.2.bias", "outconv2.0.block.4.weight", "outconv2.0.block.4.bias", "outconv2.0.block.6.weight", "outconv2.0.block.6.bias". 
	Unexpected key(s) in state_dict: "outconv1.7.weight", "outconv1.7.bias", "outconv1.8.weight", "outconv1.8.bias", "outconv1.8.running_mean", "outconv1.8.running_var", "outconv1.8.num_batches_tracked", "outconv1.0.weight", "outconv1.0.bias", "outconv1.3.block.0.weight", "outconv1.3.block.0.bias", "outconv1.3.block.2.weight", "outconv1.3.block.2.bias", "outconv1.3.block.4.weight", "outconv1.3.block.4.bias", "outconv1.3.block.6.weight", "outconv1.3.block.6.bias", "outconv1.4.running_mean", "outconv1.4.running_var", "outconv1.4.num_batches_tracked", "stage2.7.block.0.weight", "stage2.7.block.0.bias", "stage2.7.block.2.weight", "stage2.7.block.2.bias", "stage2.7.block.4.weight", "stage2.7.block.4.bias", "stage2.7.block.6.weight", "stage2.7.block.6.bias", "stage2.8.weight", "stage2.8.bias", "stage2.8.running_mean", "stage2.8.running_var", "stage2.8.num_batches_tracked", "stage2.0.weight", "stage2.0.bias", "stage2.3.block.0.weight", "stage2.3.block.0.bias", "stage2.3.block.2.weight", "stage2.3.block.2.bias", "stage2.3.block.4.weight", "stage2.3.block.4.bias", "stage2.3.block.6.weight", "stage2.3.block.6.bias", "stage2.4.weight", "stage2.4.bias", "stage2.4.running_mean", "stage2.4.running_var", "stage2.4.num_batches_tracked", "outconv2.0.weight", "outconv2.0.bias", "outconv2.5.weight", "outconv2.5.bias", "outconv2.5.running_mean", "outconv2.5.running_var", "outconv2.5.num_batches_tracked", "container1.4.weight", "container1.4.bias", "container1.4.running_mean", "container1.4.running_var", "container1.4.num_batches_tracked", "container1.3.weight", "container1.3.bias". 
	size mismatch for stage1.7.block.0.weight: copying a param with shape torch.Size([32, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 64, 1, 1]).
	size mismatch for stage1.7.block.0.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for stage1.7.block.2.weight: copying a param with shape torch.Size([32, 32, 3, 1]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 1]).
	size mismatch for stage1.7.block.2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for stage1.7.block.4.weight: copying a param with shape torch.Size([32, 32, 1, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 1, 3]).
	size mismatch for stage1.7.block.4.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for stage1.7.block.6.weight: copying a param with shape torch.Size([128, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 16, 1, 1]).
	size mismatch for stage1.7.block.6.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for stage1.8.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for stage1.8.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for stage1.8.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for stage1.8.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for outconv1.4.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128, 128, 1, 1]).
	size mismatch for outconv1.4.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for container1.0.weight: copying a param with shape torch.Size([256, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([384, 1, 3, 3]).
	size mismatch for container1.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for container1.1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for container1.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for container1.1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for container1.1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for container2.weight: copying a param with shape torch.Size([77, 256, 1, 13]) from checkpoint, the shape in current model is torch.Size([77, 384, 1, 17]).

Process finished with exit code 1

**Comment by yyamx** [comment]
> > 可以
> 
> 请问我参数填的是这样的 def parse_args(): parser = argparse.ArgumentParser() parser.add_argument("--task", type=str, default="val", help="task to run, test or val") parser.add_argument("--config", default=r'E:\PycharmProjects\Vehicle_Detection\license-plate-recoginition-main\license-plate-recoginition-main\workspace\lp0211\logs-2022-02-28-15-51-23\train_cfg.yml', type=str, help="model config file(.yml) path") parser.add_argument("--model", default=r'E:\PycharmProjects\Vehicle_Detection\license-plate-recoginition-main\license-plate-recoginition-main\workspace\lp_model_best.pth', type=str, help="ckeckpoint file(.ckpt) path") parser.add_argument("--path", default=r'E:\PycharmProjects\Vehicle_Detection\plate_main\plate_main\inference\images\12.jpg', type=str, help="img path") 但还是报错： C:\Users\wangwy\Anaconda3\python.exe E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:252: FutureWarning: IAAAdditiveGaussianNoise is deprecated. Please use GaussNoise instead warnings.warn("IAAAdditiveGaussianNoise is deprecated. Please use GaussNoise instead", FutureWarning) C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:290: FutureWarning: This IAAPiecewiseAffine is deprecated. Please use PiecewiseAffine instead warnings.warn("This IAAPiecewiseAffine is deprecated. Please use PiecewiseAffine instead", FutureWarning) C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:222: FutureWarning: IAASharpen is deprecated. Please use Sharpen instead warnings.warn("IAASharpen is deprecated. Please use Sharpen instead", FutureWarning) C:\Users\wangwy\Anaconda3\lib\site-packages\albumentations\imgaug\transforms.py:165: FutureWarning: This augmentation is deprecated. Please use Emboss instead warnings.warn("This augmentation is deprecated. Please use Emboss instead", FutureWarning) [LP-rec][02-28 16:13:30]INFO:Creating model... initial net weights successful! Traceback (most recent call last): File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py", line 121, in main(args) File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py", line 92, in main LP_Rec = Perdictor(cfg, args.model, logger,) File "E:/PycharmProjects/Vehicle_Detection/license-plate-recoginition-main/license-plate-recoginition-main/inference.py", line 52, in **init** self.task.model.load_state_dict(ckpt["state_dict"]) File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1224, in load_state_dict self.**class**.**name**, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for PlateNet_multi_1: Missing key(s) in state_dict: "outconv1.0.block.0.weight", "outconv1.0.block.0.bias", "outconv1.0.block.2.weight", "outconv1.0.block.2.bias", "outconv1.0.block.4.weight", "outconv1.0.block.4.bias", "outconv1.0.block.6.weight", "outconv1.0.block.6.bias", "stage2.0.block.0.weight", "stage2.0.block.0.bias", "stage2.0.block.2.weight", "stage2.0.block.2.bias", "stage2.0.block.4.weight", "stage2.0.block.4.bias", "stage2.0.block.6.weight", "stage2.0.block.6.bias", "stage2.4.block.0.weight", "stage2.4.block.0.bias", "stage2.4.block.2.weight", "stage2.4.block.2.bias", "stage2.4.block.4.weight", "stage2.4.block.4.bias", "stage2.4.block.6.weight", "stage2.4.block.6.bias", "stage2.5.weight", "stage2.5.bias", "stage2.5.running_mean", "stage2.5.running_var", "outconv2.0.block.0.weight", "outconv2.0.block.0.bias", "outconv2.0.block.2.weight", "outconv2.0.block.2.bias", "outconv2.0.block.4.weight", "outconv2.0.block.4.bias", "outconv2.0.block.6.weight", "outconv2.0.block.6.bias". Unexpected key(s) in state_dict: "outconv1.7.weight", "outconv1.7.bias", "outconv1.8.weight", "outconv1.8.bias", "outconv1.8.running_mean", "outconv1.8.running_var", "outconv1.8.num_batches_tracked", "outconv1.0.weight", "outconv1.0.bias", "outconv1.3.block.0.weight", "outconv1.3.block.0.bias", "outconv1.3.block.2.weight", "outconv1.3.block.2.bias", "outconv1.3.block.4.weight", "outconv1.3.block.4.bias", "outconv1.3.block.6.weight", "outconv1.3.block.6.bias", "outconv1.4.running_mean", "outconv1.4.running_var", "outconv1.4.num_batches_tracked", "stage2.7.block.0.weight", "stage2.7.block.0.bias", "stage2.7.block.2.weight", "stage2.7.block.2.bias", "stage2.7.block.4.weight", "stage2.7.block.4.bias", "stage2.7.block.6.weight", "stage2.7.block.6.bias", "stage2.8.weight", "stage2.8.bias", "stage2.8.running_mean", "stage2.8.running_var", "stage2.8.num_batches_tracked", "stage2.0.weight", "stage2.0.bias", "stage2.3.block.0.weight", "stage2.3.block.0.bias", "stage2.3.block.2.weight", "stage2.3.block.2.bias", "stage2.3.block.4.weight", "stage2.3.block.4.bias", "stage2.3.block.6.weight", "stage2.3.block.6.bias", "stage2.4.weight", "stage2.4.bias", "stage2.4.running_mean", "stage2.4.running_var", "stage2.4.num_batches_tracked", "outconv2.0.weight", "outconv2.0.bias", "outconv2.5.weight", "outconv2.5.bias", "outconv2.5.running_mean", "outconv2.5.running_var", "outconv2.5.num_batches_tracked", "container1.4.weight", "container1.4.bias", "container1.4.running_mean", "container1.4.running_var", "container1.4.num_batches_tracked", "container1.3.weight", "container1.3.bias". size mismatch for stage1.7.block.0.weight: copying a param with shape torch.Size([32, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 64, 1, 1]). size mismatch for stage1.7.block.0.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]). size mismatch for stage1.7.block.2.weight: copying a param with shape torch.Size([32, 32, 3, 1]) from checkpoint, the shape in current model is torch.Size([16, 16, 3, 1]). size mismatch for stage1.7.block.2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]). size mismatch for stage1.7.block.4.weight: copying a param with shape torch.Size([32, 32, 1, 3]) from checkpoint, the shape in current model is torch.Size([16, 16, 1, 3]). size mismatch for stage1.7.block.4.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([16]). size mismatch for stage1.7.block.6.weight: copying a param with shape torch.Size([128, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 16, 1, 1]). size mismatch for stage1.7.block.6.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]). size mismatch for stage1.8.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]). size mismatch for stage1.8.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]). size mismatch for stage1.8.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]). size mismatch for stage1.8.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]). size mismatch for outconv1.4.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128, 128, 1, 1]). size mismatch for outconv1.4.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]). size mismatch for container1.0.weight: copying a param with shape torch.Size([256, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([384, 1, 3, 3]). size mismatch for container1.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]). size mismatch for container1.1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]). size mismatch for container1.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]). size mismatch for container1.1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]). size mismatch for container1.1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]). size mismatch for container2.weight: copying a param with shape torch.Size([77, 256, 1, 13]) from checkpoint, the shape in current model is torch.Size([77, 384, 1, 17]).
> 
> Process finished with exit code 1

请问您解决了嘛 我也遇到了这个问题

**Comment by ChHanXiao** [comment]
模型已更新

**Comment by yyamx** [comment]
> 模型已更新

您好，我想问一下您更新的权重文件训练数据集包括哪些部分，是不是没有黄牌挂车一类的

**Comment by yyamx** [comment]
此外我想问一下生成车牌程序gen_data.py修改哪里可以更改生成的车牌类型，目前只是生成绿牌
gen = GenData(sum_path=SMU_PATH, bg_path=BG_PATH, cfg=cfg)

**Comment by ChHanXiao** [comment]
生成配置文件[config_gen.py](https://github.com/ChHanXiao/license-plate-recoginition/blob/main/data/config_gen.py)，列出的支持车牌种类都可以生成，在生成数据集上单双行都可以达到比较高的指标，实际使用想要提升还是需要添加真实数据，或者针对性的数据增强

**Comment by yyamx** [comment]
> 生成配置文件[config_gen.py](https://github.com/ChHanXiao/license-plate-recoginition/blob/main/data/config_gen.py)，列出的支持车牌种类都可以生成，在生成数据集上单双行都可以达到比较高的指标，实际使用想要提升还是需要添加真实数据，或者针对性的数据增强

在gen_data.py中，具体的修改车牌类型的在哪比如生成黄牌，我没有实验成功，感谢！

**Comment by ChHanXiao** [comment]
就是配置文件啊[config_gen.py](https://github.com/ChHanXiao/license-plate-recoginition/blob/main/data/config_gen.py)，可以修改每类车牌的生成概率 cfg.p = [0.,0.,0.,1,0.,0.,0.] #[black_plate,blue_plate,yellow_plate,green_plate,white_plate,farm_plate,airport]，以及每类车牌中的概率

**Comment by sweetboxwwy** [comment]
> 模型已更新

inference.py第102句target = meta["img_info"]["file_name"].split('-')[2]报错：IndexError: list index out of range。麻烦博主解答一下

**Comment by ChHanXiao** [comment]
标签以文件名方式存的，用来评估指标的，只要推理看着改下就好~

**Comment by sweetboxwwy** [comment]
> 标签以文件名方式存的，用来评估指标的，只要推理看着改下就好~

运行发现meta["img_info"]["file_name"]是11.jpg ， result[0]是川240，这是不是识别错误了，试了好几张图片都是三个数字

**Comment by yyamx** [comment]
博主 生成的车牌颜色对不上不影响训练效果吧，比如生成的蓝牌，车牌颜色确实棕色而不是蓝色

**Comment by ChHanXiao** [comment]
输入车牌要关键点对齐，训练集中加入了很多增强，颜色影响不大

**Comment by yyamx** [comment]
博主您好，我想问一下训练的数据的命名必须是您的生成车牌的命名规则那样的还是说LPRnet网络训练车牌时，命名只是车牌号就行。

**Comment by ChHanXiao** [comment]
我只是训练是读取文件名作为label，自己可以根据需要改
