### ISSUE TITLE
测试程序在哪

### ISSUE THREAD

**Issue by yyamx** [ChHanXiao/license-plate-recoginition#2]
代码里的权重是否包含特殊车辆和双行车牌的训练，测试代码在哪里还是自己写一个

**Comment by ChHanXiao** [comment]
参考[inference.py](https://github.com/ChHanXiao/license-plate-recoginition/blob/main/inference.py)

**Comment by yyamx** [comment]
>您好还是有点错误呢

- File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1224, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PlateNet_multi_1:
	Missing key(s) in state_dict: "outconv1.0.block.0.weight", "outconv1.0.block.0.bias", "outconv1.0.block.2.weight", "outconv1.0.block.2.bias", "ou

**Comment by yyamx** [comment]
博主您好，最近在尝试将博主的识别网络和yolov5车牌定位级联起来，出现了错误，想请教一下。  File "E:/yolo_carcar/detect.py", line 222, in <module>
    detect()
  File "E:/yolo_carcar/detect.py", line 90, in detect
    pred,plat_num = apply_classifier(pred, modelc, img, im0s)
  File "E:\yolo_carcar\utils1\utils.py", line 880, in apply_classifier
    preds = model(torch.Tensor(ims).to(d.device))  # classifier prediction
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 890, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\yolo_carcar\model\LPRNet.py", line 215, in forward
    logits = torch.cat((out1, out2), 1)     # 384x4x20
RuntimeError: Sizes of tensors must match except in dimension 2. Got 1 and 2 (The offending index is 0)

**Comment by ChHanXiao** [comment]
debug一下，输入的大小不对

**Comment by yyamx** [comment]
博主您好，我之前用的是18年论文的LPR网络做的级联，效果可以，然后用这个网络（为了识别双行车牌和特殊车辆）与yolo做级联调通以后出现以下问题，想请教一下是哪方面的原因
![捕获](https://user-images.githubusercontent.com/86865960/157179498-9e200308-0028-4cce-8a4b-6291b5c1f323.PNG)

**Comment by ChHanXiao** [comment]
应该是输出的维度顺序不一样了，permute下，对照下后处理

**Comment by yyamx** [comment]
感谢博主指导，另外博主如何消除这种‘-’情况
![捕获](https://user-images.githubusercontent.com/86865960/157201581-02d84178-4bb8-4ac7-8135-54bd88259a48.PNG)

**Comment by ChHanXiao** [comment]
后处理没写好吧 = =

**Comment by yyamx** [comment]
博主您好，我用权重预测字母R都不能预测出来是什么原因呢，用博主的权重预测的
![捕获](https://user-images.githubusercontent.com/86865960/157665330-e1a431c7-a710-4b4d-ad32-86be19d1a216.PNG)

**Comment by ChHanXiao** [comment]
抱歉忘记回复了，应该没问题的，R并不特殊啊，晚上回去我确认下~

**Comment by yyamx** [comment]
> 抱歉忘记回复了，应该没问题的，R并不特殊啊，晚上回去我确认下~

打扰博主了，我这里确实R都不能识别，望博主帮助感谢感谢

**Comment by ChHanXiao** [comment]
![20220108-blue-川AF5R53-1641619202190322](https://user-images.githubusercontent.com/24456969/159023145-97dd7338-dd90-4e72-bae2-eb05c55af23f.png)
看上去没问题呢

**Comment by yyamx** [comment]
> ![20220108-blue-川AF5R53-1641619202190322](https://user-images.githubusercontent.com/24456969/159023145-97dd7338-dd90-4e72-bae2-eb05c55af23f.png) 看上去没问题呢

博主我和Yolo网络进行级联的然后就只有R识别不出来呢，哪方面问题呢想请教
![川R4A304](https://user-images.githubusercontent.com/86865960/159026330-d8f765f0-0d28-436b-b86d-a66eb11bf308.jpg)
