### ISSUE TITLE
数据生成时候，如果要加入新的字体，还有背景要怎么弄

### ISSUE THREAD

**Issue by gaoyuchris** [ChHanXiao/license-plate-recoginition#3]

**Comment by ChHanXiao** [comment]
在`data/chinese/`有所有车牌的生成，都是用的分割好的字符，如果是想通过字体生成的话参考这个https://github.com/ufownl/fake_chs_lp/blob/master/black_plate.py
背景贴图在gen_data.py  中gen = GenData(sum_path=SMU_PATH, bg_path=BG_PATH, cfg=cfg)，怎么贴可按照需要修改

**Comment by gaoyuchris** [comment]
> 在`data/chinese/`有所有车牌的生成，都是用的分割好的字符，如果是想通过字体生成的话参考这个https://github.com/ufownl/fake_chs_lp/blob/master/black_plate.py 背景贴图在gen_data.py 中gen = GenData(sum_path=SMU_PATH, bg_path=BG_PATH, cfg=cfg)，怎么贴可按照需要修改

@ChHanXiao 了解，我的意思是车牌的底图是怎么生成的，也有相关的代码么？

**Comment by gaoyuchris** [comment]
另外还有一个问题，我看下载下来的模型，单层识别效果还挺好的。双层的车牌，针对生成的数据进行测试，识别效果也不行，这个模型有加入双层的数据进行训练么

**Comment by ChHanXiao** [comment]
底层图片需要自己找了；双层指标问题我也发现了，现在实验结果是，需要多个分支拼接双层指标才会有提升，三个尺度的拼接指标要更好点，我还在测试~

**Comment by gaoyuchris** [comment]
> 底层图片需要自己找了；双层指标问题我也发现了，现在实验结果是，需要多个分支拼接双层指标才会有提升，三个尺度的拼接指标要更好点，我还在测试~

好嘞，感谢，我在网上看到有一个资料，不知道有没有用，可以参考一下https://blog.csdn.net/qq_39056987/article/details/120011094， 期待你的更新

**Comment by yyamx** [comment]
博主您好，我发现博主的权重文件好像不能识别出字母R，这是怎么回事

**Comment by yyamx** [comment]
> 另外还有一个问题，我看下载下来的模型，单层识别效果还挺好的。双层的车牌，针对生成的数据进行测试，识别效果也不行，这个模型有加入双层的数据进行训练么

您的R字母识别效果如何

**Comment by gaoyuchris** [comment]
> > 另外还有一个问题，我看下载下来的模型，单层识别效果还挺好的。双层的车牌，针对生成的数据进行测试，识别效果也不行，这个模型有加入双层的数据进行训练么
> 
> 您的R字母识别效果如何

我随便测了一张，感觉还行

**Comment by yyamx** [comment]
> > > 另外还有一个问题，我看下载下来的模型，单层识别效果还挺好的。双层的车牌，针对生成的数据进行测试，识别效果也不行，这个模型有加入双层的数据进行训练么
> > 
> > 
> > 您的R字母识别效果如何
> 
> 我随便测了一张，感觉还行
博主训练的都是生成的假车牌嘛，另外训练的batch和迭代次数设置多少合适呢
